Repository tinkerbell/tink, pull requests merged in 2020-08, with the labels that each got.

#216 Fix Issue #196: Filtered the workflow context sent to worker by server
  cmd/tink-worker/action.go
  cmd/tink-worker/worker.go
  db/workflow.go
  executor/executor.go
  grpc-server/tinkerbell.go
  protos/workflow/workflow.pb.go
  protos/workflow/workflow.pb.gw.go
  protos/workflow/workflow.proto
Labels: enhancement

#231 Disable tk client setup if an --help flag is present
  cmd/tink-cli/cmd/root.go
Labels: area/tink-cli, ready-to-merge

#234 Removed redundant documentation from tink repository
  README.md
  docs/architecture.md
  docs/cli/README.md
  docs/cli/hardware.md
  docs/cli/template.md
  docs/cli/workflow.md
  docs/components.md
  docs/concepts.md
  docs/examples/hello-world.tmpl
  docs/hello-world.md
  docs/img/ephemeral-data.png
  docs/img/workflow-architecture.png
  docs/setup.md
  docs/troubleshoot.md
  docs/writing-workflow.md
Labels: documentation, ready-to-merge

#237 Added a new rpc call workflow.GetWorkflowContextList to be used by boots
  db/workflow.go
  executor/executor.go
  go.mod
  grpc-server/tinkerbell.go
  protos/workflow/workflow.pb.go
  protos/workflow/workflow.pb.gw.go
  protos/workflow/workflow.proto
Labels: P1, bug, fix-required, ready-to-merge

#239 Make golint-ci happy
  cmd/tink-cli/cmd/hardware/all.go
  cmd/tink-cli/cmd/hardware/watch.go
  cmd/tink-cli/cmd/template/create.go
  cmd/tink-cli/cmd/template/list.go
  cmd/tink-cli/cmd/workflow/create.go
  cmd/tink-cli/cmd/workflow/get.go
  cmd/tink-cli/cmd/workflow/list.go
  cmd/tink-cli/cmd/workflow/state.go
  cmd/tink-cli/main.go
  cmd/tink-worker/action.go
  cmd/tink-worker/worker.go
  db/template.go
  db/workflow.go
  executor/executor.go
  go.mod
  go.sum
  grpc-server/hardware.go
  http-server/http_handlers.go
  http-server/http_handlers_test.go
  http-server/http_server.go
  test/framework/hardware.go
  test/framework/setup.go
  test/framework/template.go
  test/framework/worker.go
Labels: ready-to-merge

#240 fix go vet
  db/workflow.go
  grpc-server/workflow.go
Labels: ready-to-merge

#235 Move to GitHub action from Drone
  .github/workflows/ci.yaml
Labels: ready-to-merge

#242 Remove drone configuration
  .drone.yml
Labels: ready-to-merge

#244 fix binary permission during ci
  .github/workflows/ci.yaml
Labels: area/ci-cd-release, ready-to-merge

#245 fix download artifact during docker build job
  .github/workflows/ci.yaml
Labels: area/ci-cd-release, ready-to-merge

#247 Refactoring db package for unit tests
  db/db.go
  db/hardware.go
  db/mock/hardware.go
  db/mock/mock.go
  db/mock/template.go
  db/mock/workflow.go
  db/template.go
  db/workflow.go
  executor/executor.go
  go.mod
  go.sum
  grpc-server/grpc_server.go
  grpc-server/hardware.go
  grpc-server/template.go
  grpc-server/tinkerbell.go
  grpc-server/workflow.go
Labels: enhancement, ready-to-merge

#249 Fixed log levels in worker code
  cmd/tink-worker/action.go
Labels: fix-required, ready-to-merge

#248 Unit tests for workflow RPC service
  db/mock/workflow.go
  db/workflow.go
  grpc-server/tinkerbell.go
  grpc-server/tinkerbell_test.go
Labels: ready-to-merge

#255 Removal of Packet references
  http-server/http_server.go
  test/_vagrant/vagrant_test.go
Labels: P3, ready-to-merge, size/S

#260 Fix log message contains JSON
  grpc-server/tinkerbell.go
Labels: P3, ready-to-merge, size/XS

#254 Fix for Terraform provisioning #103
  deploy/terraform/install_package.sh
  deploy/terraform/main.tf
Labels: bug, ready-to-merge

#251 Versions and completions
  .gitignore
  Makefile
  client/main.go
  cmd/tink-cli/.gitignore
  cmd/tink-cli/cmd/completion.go
  cmd/tink-cli/cmd/root.go
  cmd/tink-cli/main.go
  cmd/tink-server/main.go
  cmd/tink-worker/action.go
  cmd/tink-worker/main.go
  go.mod
  go.sum
Labels: ready-to-merge

#261 Add codecov as part of ci checks
  .github/workflows/ci.yaml
  README.md
Labels: ready-to-merge

#256 Revisiting tests to have reusable mocks
  db/mock/mock.go
  db/mock/workflow.go
  go.mod
  go.sum
  grpc-server/tinkerbell_test.go
Labels: P2, added-tests, ready-to-merge, size/L

#262 Increase go test timeout for vagrant tests
  .github/workflows/vagrant-packet.yaml
  go.mod
Labels: area/ci-cd-release, ready-to-merge

#263 Fixed log message format
  grpc-server/tinkerbell.go
  grpc-server/workflow.go
Labels: P3, bug, ready-to-merge, size/XS

#268 terraform: remove extra bracket
  deploy/terraform/main.tf
Labels: ready-to-merge
