Repository tinkerbell/tink, pull requests merged in 2020-07, with the labels that each got.

#200 Added workflow client to connect to tink. Boots issue #35
  client/main.go
Labels: enhancement, fix-required, ready-to-merge

#191 updated json example in docs to new structure
  docs/hello-world.md
Labels: documentation, ready-to-merge

#205 Fix issue #204: Added validation to avoid duplication of mac addresses in the hardware database
  grpc-server/hardware.go
Labels: enhancement, ready-to-merge

#207 Fix issue #150: Modified the behaviour of few "tink hardware cli"
  cmd/tink-cli/cmd/hardware/all.go
  cmd/tink-cli/cmd/hardware/commands.go
  cmd/tink-cli/cmd/hardware/ip.go
  cmd/tink-cli/cmd/hardware/mac.go
  cmd/tink-cli/cmd/hardware/push.go
  metrics/metrics.go
Labels: enhancement, ready-to-merge

#215 Update generate-envrc.sh
  generate-envrc.sh
Labels: area/setup, ready-to-merge

#220 chore: gitignore files generated during vagrant provisioning
  .gitignore
Labels: P3, area/setup, ready-to-merge, size/XS

#221 chore: expose tink server via Vagrant port forward
  deploy/vagrant/Vagrantfile
Labels: area/setup, ready-to-merge, size/XS

#223 Corrected env variable in error message
  cmd/tink-worker/worker.go
Labels: size/XS

#224 [WIP] e2e test for vagrant setup
  .github/workflows/vagrant-packet.yaml
  deploy/vagrant/Vagrantfile
  go.mod
  test/_vagrant/vagrant.go
  test/_vagrant/vagrant_test.go
Labels: area/ci-cd-release, ci-check/vagrant-setup, ready-to-merge, size/M
