Repository tinkerbell/tink, pull requests merged in 2020-12, with the labels that each got.

#366 Tink-cli unit tests
  cmd/tink-cli/cmd/docs_test.go
  cmd/tink-cli/cmd/hardware_test.go
  cmd/tink-cli/cmd/template_test.go
  cmd/tink-cli/cmd/workflow_test.go
Labels: ready-to-merge

#275 ENG-8624 fix operating_system_version/operating_system mismatch
  protos/packet/packet.pb.go
  protos/packet/packet.proto
Labels: ready-to-merge

#371 Fix #363: Creation of template with the same name
  cmd/tink-cli/cmd/template/create.go
  db/db.go
  db/migration/202012041103-remove-unique-constraints.go
  db/migration/migration.go
  db/mock/mock.go
  db/mock/template.go
  db/mock/workflow.go
  db/template.go
  grpc-server/template.go
  grpc-server/template_test.go
  grpc-server/workflow.go
  grpc-server/workflow_test.go
Labels: bug, ready-to-merge

#301 Implementation for event driven tink
  .codespell-whitelist
  client/informers/informer.go
  client/informers/informer_test.go
  client/informers/mock.go
  client/informers/notification.go
  client/informers/notification_test.go
  client/listener/listener.go
  client/main.go
  cmd/tink-cli/cmd/events.go
  cmd/tink-cli/cmd/events/commands.go
  cmd/tink-cli/cmd/events/watch.go
  cmd/tink-cli/cmd/hardware/watch.go
  cmd/tink-server/main.go
  db/db.go
  db/events.go
  db/events/purge.go
  db/migration/202010071530-init-events-table-and-triggers.go
  db/migration/migration.go
  db/mock/events.go
  go.mod
  go.sum
  grpc-server/events.go
  grpc-server/grpc_server.go
  grpc-server/hardware.go
  protos/events/events.pb.go
  protos/events/events.proto
  protos/hardware/hardware.pb.go
  protos/hardware/hardware.proto
Labels: enhancement, ready-to-merge

#383 Fix migration id for template name key
  db/migration/202012041103-remove-unique-constraints.go
Labels: ready-to-merge

#378 ENG-11253: create partial unique index on template
  db/migration/202012091055-add-partial-unique-constraint-on-template.go
  db/migration/migration.go
  db/template.go
Labels: ready-to-merge

#386 Remove global logger from db package
  cmd/tink-server/main.go
  db/db.go
  db/events.go
  db/hardware.go
  db/template.go
  db/workflow.go
Labels: ready-to-merge

#388 Add reflection to grpc service
  grpc-server/grpc_server.go
Labels: ready-to-merge

#384 CII Best Practices Badge
  README.md
Labels: ready-to-merge

#392 db: Remove hard coded role in 202010071530.
  db/migration/202010071530-init-events-table-and-triggers.go
Labels: ready-to-merge

#387 Setup integration test suite for db package
  db/db_test.go
  db/template.go
  db/template_test.go
  db/testdata/template_happy_path_1.yaml
  go.mod
  go.sum
  workflow/template_validator.go
  workflow/template_validator_test.go
  workflow/types.go
Labels: ci-check/vagrant-setup, ready-to-merge

#397 Replace CI build badge
  .github/workflows/ci.yaml
  README.md
Labels: ready-to-merge

#398 Link to action runs, not the badge
  README.md
Labels: ready-to-merge

#395 Fixed: duplicate key value violates unique constraint while creating multiple workflows
  db/migration/2020121691335-update-events-primary-key.go
  db/migration/migration.go
Labels: P1, ready-to-merge

#402 Only display template IDs
  cmd/tink-cli/cmd/template/list.go
Labels: enhancement

#401 db tests for hardware events
  db/events_test.go
  db/testdata/hardware.json
Labels: ready-to-merge

#404 Fixed: consistent user experience across tink-cli list command -q
  cmd/tink-cli/cmd/hardware/all.go
  cmd/tink-cli/cmd/hardware/list.go
  cmd/tink-cli/cmd/template/list.go
  cmd/tink-cli/cmd/workflow/list.go
Labels: enhancement, ready-to-merge

#408 Must parse rendered template for hardware address validation
  grpc-server/workflow.go
  grpc-server/workflow_test.go
  workflow/template_validator.go
  workflow/template_validator_test.go
Labels: P2
