Repository tinkerbell/tink, pull requests merged in 2020-10, with the labels that each got.

#313 Apply migrations when tink-server boots
  cmd/tink-server/main.go
  db/db.go
  db/migration/202009171251-init-database.go
  db/migration/migration.go
  deploy/docker-compose.yml
  go.mod
  go.sum
  grpc-server/grpc_server.go
Labels: ready-to-merge

#287 tink worker command line args
  cmd/tink-worker/action.go
  cmd/tink-worker/cmd/root.go
  cmd/tink-worker/internal/action.go
  cmd/tink-worker/internal/registry.go
  cmd/tink-worker/internal/worker.go
  cmd/tink-worker/main.go
  go.mod
  http-server/http_handlers.go
Labels: needs-docs, ready-to-merge

#315 Move workflow stuff out of pkg
  db/template.go
  db/workflow.go
  http-server/http_handlers.go
  pkg/template_validator.go
  pkg/template_validator_test.go
  workflow/template_validator.go
  workflow/template_validator_test.go
  workflow/types.go
Labels: bc-break, ready-to-merge

#322 [tink-worker] Fix use and defaulting of the max-retry flag
  cmd/tink-worker/cmd/root.go
Labels: ready-to-merge

#337 Tink CLI errors now end with a newline
  cmd/tink-cli/main.go
  go.mod
Labels: ready-to-merge, size/XS

#341 Migrating docker action from v1 to v2 in GH Action
  .github/workflows/ci.yaml
Labels: ready-to-merge

#343 Quay login only works if commit is in master
  .github/workflows/ci.yaml
Labels: ready-to-merge

#342 ENG-9317 Fix concurrent workflow create bug
  db/workflow.go
Labels: ready-to-merge

#346 Fix concurrent workflow create bug by unique index
  db/migration/202010221010-add-unique-index.go
  db/migration/migration.go
  db/workflow.go
Labels: ready-to-merge

#348 Raise create work flow isolation back to Serializable
  db/workflow.go
  deploy/db/tinkerbell-init.sql
Labels: ready-to-merge

#351 Fix fmt in ci
  .github/workflows/ci.yaml
  cmd/tink-cli/cmd/hardware/commands.go
  cmd/tink-cli/cmd/hardware/id.go
  cmd/tink-cli/cmd/hardware/push.go
  cmd/tink-cli/cmd/hardware/watch.go
  db/migration/202010221010-add-unique-index.go
  grpc-server/tinkerbell_test.go
  http-server/http_handlers.go
  http-server/http_handlers_test.go
  http-server/http_server.go
  shell.nix
Labels: ready-to-merge

#345 Show protos some love
  .editorconfig
  CONTRIBUTING.md
  client/main.go
  cmd/tink-cli/cmd/workflow/data.go
  cmd/tink-cli/cmd/workflow/state.go
  cmd/tink-worker/cmd/root.go
  cmd/tink-worker/internal/action.go
  cmd/tink-worker/internal/worker.go
  db/workflow.go
  go.mod
  go.sum
  grpc-server/grpc_server.go
  grpc-server/template.go
  grpc-server/tinkerbell.go
  grpc-server/tinkerbell_test.go
  grpc-server/workflow.go
  http-server/http_handlers.go
  protodep.lock
  protodep.toml
  protos/.gitignore
  protos/common/timestamp.proto
  protos/hardware/hardware.pb.go
  protos/hardware/hardware.pb.gw.go
  protos/hardware/hardware.proto
  protos/packet/packet.pb.go
  protos/packet/packet.proto
  protos/protoc.sh
  protos/template/template.pb.go
  protos/template/template.pb.gw.go
  protos/template/template.proto
  protos/workflow/workflow.pb.go
  protos/workflow/workflow.pb.gw.go
  protos/workflow/workflow.proto
  shell.nix
  test/_vagrant/vagrant_test.go
  test/e2e_test.go
  test/framework/worker.go
  test/framework/workflow.go
  test/test_wf_with_multi_workers.go
  test/test_wf_with_worker.go
  tools.go
Labels: ready-to-merge

#323 Build binaries as part of Docker
  .dockerignore
  .github/workflows/ci.yaml
  cmd/tink-cli/Dockerfile
  cmd/tink-server/Dockerfile
  cmd/tink-worker/Dockerfile
Labels: ready-to-merge

#353 Hotfix login to quay
  .github/workflows/ci.yaml
Labels: ready-to-merge

#355 Fix login to quay only in master
  .github/workflows/ci.yaml
Labels: ready-to-merge

#356 Fix compose now that we build binaries in Docker
  deploy/docker-compose.yml
Labels: ready-to-merge
