Repository tinkerbell/tink, pull requests merged in 2020-09, with the labels that each got.

#270 Fixed the duplicate name issue while creating a template
  db/mock/template.go
  deploy/db/tinkerbell-init.sql
  grpc-server/template.go
  grpc-server/template_test.go
  grpc-server/tinkerbell_test.go
Labels: P2, bug, ready-to-merge

#272 add "tink docs" command for markdown and man page generation
  cmd/tink-cli/cmd/completion.go
  cmd/tink-cli/cmd/docs.go
  cmd/tink-cli/cmd/docs_test.go
  cmd/tink-cli/cmd/root.go
  go.mod
  go.sum
Labels: area/tink-cli, documentation, enhancement

#276 Fix Terraform setup
  deploy/terraform/hardware_data.tpl
  deploy/terraform/input.tf
  deploy/terraform/install_package.sh
  deploy/terraform/main.tf
  deploy/terraform/outputs.tf
  deploy/terraform/variables.tf
  deploy/terraform/versions.tf
Labels: ready-to-merge

#285 Changed UUID package
  cmd/tink-cli/cmd/hardware/commands.go
  cmd/tink-cli/cmd/template/delete.go
  cmd/tink-cli/cmd/template/get.go
  cmd/tink-cli/cmd/template/update.go
  cmd/tink-cli/cmd/workflow/commands.go
  cmd/tink-cli/cmd/workflow/data.go
  cmd/tink-cli/cmd/workflow/delete.go
  db/db.go
  db/mock/template.go
  db/mock/workflow.go
  db/template.go
  db/workflow.go
  go.mod
  go.sum
  grpc-server/template.go
  grpc-server/workflow.go
Labels: fix-required, ready-to-merge

#283 Simple refactors
  grpc-server/hardware.go
  grpc-server/template.go
  grpc-server/workflow.go
  http-server/http_handlers.go
  protos/protoc.sh
  protos/workflow/workflow.pb.go
Labels: ready-to-merge

#286 Tink CLI now flags an error if template ID does not exist, while creating a workflow
  db/mock/mock.go
  db/mock/template.go
  db/mock/workflow.go
  db/template.go
  grpc-server/workflow.go
  grpc-server/workflow_test.go
Labels: P1, bug, ready-to-merge

#289 Move terraform to sandbox
  deploy/terraform/hardware_data.tpl
  deploy/terraform/install_package.sh
  deploy/terraform/main.tf
  deploy/terraform/outputs.tf
  deploy/terraform/variables.tf
  deploy/terraform/versions.tf
Labels: ready-to-merge

#290 Add code of conduct
  CODE_OF_CONDUCT.md
Labels: ready-to-merge

#293 Fixed #291 : tink template commands exit in case of template file does not exist
  cmd/tink-cli/cmd/template/create.go
  cmd/tink-cli/cmd/template/update.go
Labels: bug, ready-to-merge

#279 Store MAC as lowercase
  go.sum
  grpc-server/hardware.go
  grpc-server/hardware_test.go
Labels: ready-to-merge

#271 Switching from logrus to packethost/pkg/log in worker
  cmd/tink-server/main.go
  cmd/tink-worker/action.go
  cmd/tink-worker/main.go
  cmd/tink-worker/worker.go
  deploy/docker-compose.yml
  generate-envrc.sh
  go.mod
  go.sum
  grpc-server/tinkerbell_test.go
  http-server/http_handlers_test.go
Labels: enhancement, ready-to-merge

#298 Create OWNERS.md
  OWNERS.md
Labels: documentation, enhancement, ready-to-merge

#299 Update README.md
  README.md
Labels: ready-to-merge

#243 Add documentation to proto files
  protos/hardware/hardware.pb.go
  protos/hardware/hardware.proto
  protos/packet/packet.pb.go
  protos/protoc.sh
  protos/template/template.pb.go
  protos/workflow/workflow.pb.go
Labels: ready-to-merge

#302 Move docker-compose to image build.
  deploy/docker-compose.yml
Labels: ready-to-merge

#307 Fixed context path in docker-compose.yml
  deploy/docker-compose.yml
Labels: ready-to-merge, size/XS

#308 Bump golangci-lint github action
  .github/workflows/ci.yaml
Labels: ready-to-merge

#309 Terraform is not a required tool anymore
  shell.nix
Labels: ready-to-merge

#296 Apply migrations when tink-server boots
  cmd/tink-server/main.go
  db/db.go
  db/migration/202009171251-init-database.go
  db/migration/migration.go
  deploy/docker-compose.yml
  go.mod
  go.sum
  grpc-server/grpc_server.go
Labels: ready-to-merge

#310 Revert "Apply migrations when tink-server boots"
  cmd/tink-server/main.go
  db/db.go
  db/migration/202009171251-init-database.go
  db/migration/migration.go
  deploy/docker-compose.yml
  go.mod
  go.sum
  grpc-server/grpc_server.go
Labels: ready-to-merge

#280 Added the validation of template while creating it
  cmd/tink-worker/action.go
  db/mock/mock.go
  db/mock/template.go
  db/template.go
  go.mod
  grpc-server/template_test.go
  pkg/template_validator.go
  pkg/template_validator_test.go
Labels: ready-to-merge

#311 Cheerful tweaks
  deploy/docker-compose.yml
  deploy/vagrant/scripts/tinkerbell.sh
  go.mod
  go.sum
  setup.sh
  shell.nix
Labels: ready-to-merge
