Repository tinkerbell/tink, pull requests merged in 2020-06, with the labels that each got.

#124 Terraform tweaks
  .envrc
  deploy/terraform/input.tf
  deploy/terraform/main.tf
  shell.nix
Labels: area/setup

#144 Package updates
  go.mod
  go.sum
  protos/hardware/hardware.pb.go
  protos/template/template.pb.go
  protos/workflow/workflow.pb.go
  protos/workflow/workflow.proto
Labels: fix-required

#140 Accept path to OSIE tar as env for tinkerbell setup
  setup.sh
Labels: area/setup, enhancement

#148 Enable auto merge using Mergify on approval
  .mergify.yml
Labels: enhancement

#151 Tweak mergify config
  .mergify.yml
Labels: ready-to-merge

#154 Codespell fixes
  .codespell-whitelist
  .drone.yml
  ci-checks.sh
  cmd/tink-worker/action.go
  cmd/tink-worker/worker.go
  db/workflow.go
  docs/concepts.md
  grpc-server/template.go
  setup.sh
  shell.nix
  test/framework/setup.go
  test/framework/worker.go
Labels: ready-to-merge

#156 Try out setting `strict_method: rebase`
  .mergify.yml
Labels: ready-to-merge

#158 Prettification of non-code files
  .drone.yml
  README.md
  ci-checks.sh
  deploy/docker-compose.yml
  deploy/tls/ca-config.json
  docs/architecture.md
  docs/cli/README.md
  docs/cli/hardware.md
  docs/cli/template.md
  docs/cli/workflow.md
  docs/components.md
  docs/concepts.md
  docs/hello-world.md
  docs/setup.md
  docs/troubleshoot.md
  docs/writing-workflow.md
  shell.nix
  test-docker-compose.yml
  test/data/hardware/hardware_2.json
Labels: ready-to-merge

#157 ci: check shfmt
  ci-checks.sh
  hack/update-gofmt.sh
  hack/verify-gofmt.sh
  hack/verify-golint.sh
  hack/verify-govet.sh
  setup.sh
  test/build_images.sh
  test/push_images.sh
Labels: ready-to-merge

#160 Style issue with error strings
  cmd/tink-worker/main.go
  cmd/tink-worker/worker.go
  db/workflow.go
  executor/executor.go
Labels: ready-to-merge

#168 Added the nix image version '2.3.4' in the .drone.yml file
  .drone.yml
Labels: fix-required

#149 Added 'delete' command in 'tink hardware' cli
  cmd/tink-cli/cmd/hardware/all.go
  cmd/tink-cli/cmd/hardware/delete.go
  cmd/tink-cli/cmd/hardware/id.go
  cmd/tink-cli/cmd/hardware/ip.go
  cmd/tink-cli/cmd/hardware/mac.go
  cmd/tink-cli/cmd/hardware/push.go
  cmd/tink-cli/cmd/hardware/watch.go
  grpc-server/hardware.go
  protos/hardware/hardware.pb.go
  protos/hardware/hardware.proto
  protos/template/template.pb.go
  protos/workflow/workflow.pb.go
Labels: enhancement, ready-to-merge

#127 Update the README.md file
  README.md
  docs/components.md
Labels: documentation, ready-to-merge

#147 setup.sh: simplify
  deploy/docker-compose.yml
  deploy/registry/Dockerfile
  deploy/tls/entrypoint.sh
  deploy/tls/gencerts.sh
  deploy/tls/server-csr.in.json
  generate-envrc.sh
  setup.sh
  shell.nix
Labels: P1, ready-to-merge

#170 docker-compose: remove EFK
  README.md
  deploy/docker-compose.yml
  deploy/fluent-bit.conf
  docs/components.md
  docs/concepts.md
  setup.sh
Labels: ready-to-merge

#173 setup: drop git as a prereq
  setup.sh
Labels: ready-to-merge

#174 setup: certs: attempt to make the target directory
  setup.sh
Labels: ready-to-merge

#175 ci-checks: run all the checks on checked-in files; check shellcheck
  ci-checks.sh
  protos/protoc.sh
  setup.sh
  shell.nix
  test/push_images.sh
Labels: ready-to-merge

#165 Setup tinkerbell stack locally using Vagrant
  .gitignore
  deploy/vagrant/Vagrantfile
  deploy/vagrant/scripts/tinkerbell.sh
  setup.sh
Labels: area/setup, enhancement, ready-to-merge

#178 Pinned registry to 2.6
  deploy/registry/Dockerfile
Labels: ready-to-merge

#186 Vagrant: corrected location for setup process in setup script
  setup.sh
Labels: area/setup

#188 Added 4G memory for worker to prevent OOM errors when booting OSIE
  deploy/vagrant/Vagrantfile
Labels: ready-to-merge

#193 Fix for #192 added PV for postgres
  deploy/docker-compose.yml
Labels: enhancement
