Repository tinkerbell/tink, pull requests merged in 2021-09, with the labels that each got.

#528 Fix handling of os signals in tink server
  cmd/tink-server/main.go
Labels: kind/bug, priority/backlog, ready-to-merge

#519 Docker compose download link
  setup.sh
Labels: ready-to-merge

#536 Tink Server: Fix runtime panic
  go.mod
  grpc-server/grpc_server.go
Labels: kind/bug, priority/critical-urgent, kind/regression

#537 Remove unused code
  generate-env.sh
  setup.sh
  test-docker-compose.yml
  test/actions/action1/hello_world.sh
  test/actions/overwrite_data/Dockerfile
  test/actions/update_data/Dockerfile
  test/build_images.sh
  test/data/hardware/hardware_1.json
  test/data/hardware/hardware_2.json
  test/data/template/sample_1
  test/data/template/sample_2
  test/data/template/sample_3
  test/e2e_test.go
  test/framework/hardware.go
  test/framework/setup.go
  test/framework/tearDown.go
  test/framework/template.go
  test/framework/utils.go
  test/framework/worker.go
  test/framework/workflow.go
  test/push_images.sh
  test/test_wf_timeout.go
  test/test_wf_with_multi_workers.go
  test/test_wf_with_worker.go
Labels: priority/backlog, kind/cleanup
