Repository tinkerbell/tink, pull requests merged in 2021-01, with the labels that each got.

#409 Unit tests for db package
  db/events_test.go
  db/hardware_test.go
  db/template_test.go
  db/workflow_test.go
Labels: ready-to-merge

#412 Unit tests for resource Get requests
  db/hardware_test.go
  db/template_test.go
  db/workflow_test.go
Labels: ready-to-merge

#416 RenderTemplate using the text/template package, not the html one
  workflow/template_validator.go
  workflow/template_validator_test.go
Labels: ready-to-merge

#385 Fix #377: Removing name flag from the tink template create/update command
  cmd/tink-cli/cmd/template/create.go
  cmd/tink-cli/cmd/template/update.go
  cmd/tink-cli/cmd/template_test.go
Labels: bc-break, enhancement, ready-to-merge

#420 Break validate steps into their own jobs
  .github/workflows/ci.yaml
Labels: ready-to-merge

#419 Build container binaries outside of docker
  .github/workflows/ci.yaml
  Makefile
  cmd/tink-cli/.gitignore
  cmd/tink-cli/Dockerfile
  cmd/tink-server/.gitignore
  cmd/tink-server/Dockerfile
  cmd/tink-worker/.gitignore
  cmd/tink-worker/Dockerfile
Labels: ready-to-merge

#421 Simple tests for db/migration
  db/migration/202012041103-template-with-same-name-are-acceptable.go
  db/migration/migration.go
  db/migration/migration_test.go
Labels: area/ci-cd-release, ready-to-merge

#406 Bootstrap Get command for tink-cli
  .envrc
  Makefile
  client/main.go
  cmd/tink-cli/cmd/get/doc.go
  cmd/tink-cli/cmd/get/get.go
  cmd/tink-cli/cmd/get/get_test.go
  cmd/tink-cli/cmd/hardware.go
  cmd/tink-cli/cmd/hardware/delete.go
  cmd/tink-cli/cmd/hardware/get.go
  cmd/tink-cli/cmd/hardware/get_test.go
  cmd/tink-cli/cmd/hardware/id.go
  cmd/tink-cli/cmd/hardware/ip.go
  cmd/tink-cli/cmd/hardware/list.go
  cmd/tink-cli/cmd/hardware/mac.go
  cmd/tink-cli/cmd/hardware/push.go
  cmd/tink-cli/cmd/hardware/watch.go
  cmd/tink-cli/cmd/hardware_test.go
  cmd/tink-cli/cmd/root.go
  cmd/tink-cli/cmd/template.go
  cmd/tink-cli/cmd/template/commands.go
  cmd/tink-cli/cmd/template/create.go
  cmd/tink-cli/cmd/template/delete.go
  cmd/tink-cli/cmd/template/get.go
  cmd/tink-cli/cmd/template/get_test.go
  cmd/tink-cli/cmd/template/list.go
  cmd/tink-cli/cmd/template/update.go
  cmd/tink-cli/cmd/template_test.go
  cmd/tink-cli/cmd/workflow.go
  cmd/tink-cli/cmd/workflow/commands.go
  cmd/tink-cli/cmd/workflow/create.go
  cmd/tink-cli/cmd/workflow/data.go
  cmd/tink-cli/cmd/workflow/delete.go
  cmd/tink-cli/cmd/workflow/events.go
  cmd/tink-cli/cmd/workflow/get.go
  cmd/tink-cli/cmd/workflow/list.go
  cmd/tink-cli/cmd/workflow/state.go
  cmd/tink-cli/cmd/workflow_test.go
  go.mod
  go.sum
  protos/hardware/gen.go
  protos/hardware/mock.go
  protos/template/gen.go
  protos/template/mock.go
  protos/workflow/gen.go
  protos/workflow/mock.go
Labels: bc-break, ready-to-merge

#423 Remove gRPC TLS cert
  client/main.go
Labels: bc-break, ready-to-merge

#424 Revert "Remove gRPC TLS cert"
  client/main.go
Labels: ready-to-merge
