Repository tinkerbell/tink, pull requests merged in 2021-02, with the labels that each got.

#375 Document all the grpc api and generate html documentation
  Makefile
  protos/hardware/hardware.pb.go
  protos/hardware/hardware.proto
  protos/template/template.pb.go
  protos/template/template.proto
  protos/workflow/workflow.pb.go
  protos/workflow/workflow.proto
  shell.nix
Labels: ready-to-merge

#427 Nixfmt
  ci-checks.sh
  shell.nix
Labels: ready-to-merge

#430 Get path to binaries correct:
  .github/workflows/ci.yaml
Labels: ready-to-merge

#433 Reimplemented a common delete tink-cli command
  client/main.go
  cmd/tink-cli/cmd/delete/delete.go
  cmd/tink-cli/cmd/delete/delete_test.go
  cmd/tink-cli/cmd/delete/doc.go
  cmd/tink-cli/cmd/get/get_test.go
  cmd/tink-cli/cmd/hardware.go
  cmd/tink-cli/cmd/hardware/delete.go
  cmd/tink-cli/cmd/hardware_test.go
  cmd/tink-cli/cmd/template.go
  cmd/tink-cli/cmd/template/delete.go
  cmd/tink-cli/cmd/template/get.go
  cmd/tink-cli/cmd/workflow.go
  cmd/tink-cli/cmd/workflow/delete.go
  db/hardware.go
  db/template.go
  db/workflow.go
Labels: area/tink-cli, enhancement, ready-to-merge

#436 Pid namespace support
  cmd/tink-worker/internal/action.go
  db/workflow.go
  go.mod
  go.sum
  protos/workflow/workflow.pb.go
  protos/workflow/workflow.proto
  workflow/types.go
Labels: ready-to-merge

#431 Migrate tink-server to cobra and viper
  cmd/tink-server/main.go
  grpc-server/events.go
  grpc-server/grpc_server.go
  grpc-server/hardware.go
  grpc-server/template.go
  grpc-server/template_test.go
  grpc-server/tinkerbell.go
  grpc-server/tinkerbell_test.go
  grpc-server/workflow.go
  grpc-server/workflow_test.go
  http-server/http_server.go
Labels: ready-to-merge

#442 Log to stderr to notify that CLI is looking for deprecated environment
  cmd/tink-cli/cmd/delete/delete.go
  cmd/tink-cli/cmd/get/get.go
Labels: area/tink-cli, ready-to-merge

#441 Fix tink-client gRPC flags for get and delete command
  cmd/tink-cli/cmd/delete/delete.go
  cmd/tink-cli/cmd/get/get.go
Labels: area/tink-cli, ready-to-merge
