Repository tinkerbell/tink, pull requests merged in 2021-03, with the labels that each got.

#444 Fix CreatedAt, UpdatedAt for get workflow and template
  cmd/tink-cli/cmd/template/get.go
  cmd/tink-cli/cmd/template/get_test.go
  cmd/tink-cli/cmd/workflow/get.go
Labels: area/tink-cli, ready-to-merge

#446 Tink CLI Template create should use --file instead of -p
  cmd/tink-cli/cmd/template/create.go
Labels: ready-to-merge

#443 Add flag to allow you to disable tink-worker action logging rollup
  cmd/tink-worker/cmd/root.go
  cmd/tink-worker/internal/action.go
  cmd/tink-worker/internal/worker.go
Labels: ready-to-merge

#447 Fixed #381: 'tink workflow state' command returns an error if workflow does not exist
  db/workflow.go
  grpc-server/workflow.go
  grpc-server/workflow_test.go
Labels: bug, ready-to-merge

#459 Change package repository and fix build on mac
  shell.nix
Labels: ready-to-merge

#462 Revert "Change package repository and fix build on mac"
  shell.nix
Labels: ready-to-merge

#465 Typo: fist -> first
  setup.sh
Labels: ready-to-merge

#467 Add a test to assert that migrations are ordered as we declared them
  db/migration/migration_test.go
Labels: ready-to-merge

#450 docker graceful exits when image pull fails #382
  cmd/tink-worker/internal/registry.go
  cmd/tink-worker/internal/registry_test.go
Labels: enhancement, ready-to-merge

#472 Select the right self hosted runner for vagrant workflows
  .github/workflows/vagrant-packet.yaml
Labels: ready-to-merge

#474 Remove vagrant test
  .github/workflows/vagrant-packet.yaml
  go.sum
  test/_vagrant/vagrant.go
  test/_vagrant/vagrant_test.go
Labels: ready-to-merge

#473 Improve empty string test
  grpc-server/tinkerbell.go
Labels: ready-to-merge
