Repository tinkerbell/tink, pull requests merged in 2021-04, with the labels that each got.

#468 Drop the events system
  client/informers/informer.go
  client/informers/informer_test.go
  client/informers/mock.go
  client/informers/notification.go
  client/informers/notification_test.go
  client/listener/listener.go
  client/main.go
  cmd/tink-cli/cmd/events.go
  cmd/tink-cli/cmd/events/commands.go
  cmd/tink-cli/cmd/events/watch.go
  cmd/tink-cli/cmd/hardware.go
  cmd/tink-cli/cmd/hardware/watch.go
  cmd/tink-cli/cmd/hardware_test.go
  cmd/tink-server/main.go
  db/db.go
  db/events.go
  db/events/purge.go
  db/events_test.go
  db/hardware_test.go
  db/migration/2021032610300-drop-events-system.go
  db/migration/migration.go
  db/mock/events.go
  grpc-server/events.go
  grpc-server/grpc_server.go
  protos/events/events.pb.go
  protos/events/events.proto
Labels: P1, bc-break, ready-to-merge

#478 Add docker image building targets to Makefile
  .github/workflows/ci.yaml
  Makefile
  README.md
  cmd/tink-cli/Dockerfile
  cmd/tink-server/Dockerfile
  cmd/tink-worker/Dockerfile
  deploy/docker-compose.yml
  rules.mk
Labels: ready-to-merge

#483 Change envrc to .env
  .gitignore
  deploy/vagrant/scripts/tinkerbell.sh
  generate-env.sh
  setup.sh
Labels: area/setup, ready-to-merge

#476 Fix_475: Correct timestamps in get by Id commands for template and workflow
  db/db.go
  db/mock/mock.go
  db/mock/template.go
  db/template.go
  db/template_test.go
  db/workflow.go
  db/workflow_test.go
  grpc-server/template.go
  grpc-server/template_test.go
  grpc-server/workflow.go
  grpc-server/workflow_test.go
Labels: bug

#484 Update documentation
  CONTRIBUTING.md
  README.md
Labels: documentation, ready-to-merge
